on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Build docs
        run: uv run mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    permissions:
      id-token: write
      pages: write
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5

      - id: deployment
        uses: actions/deploy-pages@v4
